An Introduction to JavaScript
javascript-tutorial/nl.javascript.info pull request #2
Opened 2020-05-06 00:09 UTC by vertonghenb

2020-05-06 00:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/nl.javascript.info?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/nl.javascript.info?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/nl.javascript.info?pullRequest=2) it.</sub>

2021-04-02 20:25 UTC, noah-vdv requested changes
Just a few mishaps here and there

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +In dit aspect is JavaScript heel anders dan een andere taal die [Java](https://en.wikipedia.org/wiki/Java_(programming_language)) heet.
```suggestion
In dit aspect is JavaScript heel anders dan een andere taal die [Java](https://nl.wikipedia.org/wiki/Java_(programmeertaal)) heet.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +```smart header="Waarom heet het <u>Java</u>Script?".
```suggestion
```smart header="Waarom heet het <u>Java</u>Script?"
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +Maar naarmate het zich ontwikkelde, werd JavaScript een volledig onafhankelijke taal met een eigen specificatie genaamd [ECMAScript](http://en.wikipedia.org/wiki/ECMAScript), en nu heeft het geen enk
```suggestion
Maar naarmate het zich ontwikkelde, werd JavaScript een volledig onafhankelijke taal met een eigen specificatie genaamd [ECMAScript](https://nl.wikipedia.org/wiki/ECMAScript), en nu heeft het geen enkele relatie meer met Java.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +Tegenwoordig kan JavaScript niet alleen in de browser worden uitgevoerd, maar ook op de server, of eigenlijk op elk apparaat dat een speciaal programma heeft dat [de JavaScript-engine] heet (https://
```suggestion
Tegenwoordig kan JavaScript niet alleen in de browser worden uitgevoerd, maar ook op de server, of eigenlijk op elk apparaat dat een speciaal programma heeft dat [de JavaScript-engine](https://en.wikipedia.org/wiki/JavaScript_engine) heet.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +De browser heeft een embedded engine die soms een "JavaScript virtuele machine" wordt genoemd.
```suggestion
De browser heeft een ingebed engine die soms een "JavaScript virtuele machine" wordt genoemd.
```
Hieronder had je ook ingebed geschreven

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +De mogelijkheden van JavaScript zijn sterk afhankelijk van de omgeving waarin het draait. Bijvoorbeeld, [Node.js](https://wikipedia.org/wiki/Node.js) ondersteunt functies die JavaScript toestaan om w
```suggestion
De mogelijkheden van JavaScript zijn sterk afhankelijk van de omgeving waarin het draait. Bijvoorbeeld, [Node.js](https://nl.wikipedia.org/wiki/Node.js) ondersteunt functies die JavaScript toestaan om willekeurige bestanden te lezen/schrijven, netwerkverzoeken uit te voeren, enz.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +In-browser JavaScript kan dat bijvoorbeeld:
```suggestion
In-browser JavaScript kan bijvoorbeeld:
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +- Nieuwe HTML toe te voegen aan de pagina, de bestaande inhoud te wijzigen, stijlen aan te passen.
```suggestion
- Nieuwe HTML toe voegen aan de pagina, de bestaande inhoud wijzigen, stijlen aanpassen.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +- Verzoeken via het netwerk naar externe servers sturen, bestanden downloaden en uploaden (zogenaamde [AJAX](https://en.wikipedia.org/wiki/Ajax_(programmering)) en [COMET](https://en.wikipedia.org/wi
```suggestion
- Verzoeken via het netwerk naar externe servers sturen, bestanden downloaden en uploaden (zogenaamde [AJAX](https://nl.wikipedia.org/wiki/Asynchronous_JavaScript_and_XML) en [COMET](https://nl.wikipedia.org/wiki/Comet_(internet)) technologieën).
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +- Krijg en stel cookies, stel vragen aan de bezoeker, toon berichten.
```suggestion
- Cookies krijgen en stellen, vragen stellen aan de bezoeker, berichten tonen.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +- Onthoud de gegevens aan de klantzijde ("lokale opslag").
```suggestion
- De gegevens aan de klantzijde onthouden ("lokale opslag").
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +    Er zijn manieren om met de camera/microfoon en andere apparaten te communiceren, maar daarvoor is de uitdrukkelijke toestemming van de gebruiker nodig. Een JavaScript-pagina mag dus niet stiekem
```suggestion
    Er zijn manieren om met de camera/microfoon en andere apparaten te communiceren, maar daarvoor is de uitdrukkelijke toestemming van de gebruiker nodig. Een JavaScript-pagina mag dus niet stiekem een webcamera inschakelen, de omgeving observeren en de informatie naar de [NSA](https://nl.wikipedia.org/wiki/National_Security_Agency) sturen.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +```vergelijken
```suggestion
```compare
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +Zo is er onlangs een overvloed aan nieuwe talen verschenen, die *getranspilleerd* (geconverteerd) zijn naar JavaScript voordat ze in de browser draaien.
```suggestion
Zo is er onlangs een overvloed aan nieuwe talen verschenen, die *getransporteerd* (geconverteerd) zijn naar JavaScript voordat ze in de browser draaien.
```
At the bottom you used this multiple times so I guess this is the right one

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +- [CoffeeScript](http://coffeescript.org/) is een "syntactisch suiker" voor JavaScript. Het introduceert een kortere syntaxis, waardoor we duidelijkere en nauwkeurigere code kunnen schrijven. Gewoonl
```suggestion
- [CoffeeScript](http://coffeescript.org/) is een "syntactisch suiker" voor JavaScript. Het introduceert een kortere syntaxis, waardoor we duidelijkere en nauwkeurigere code kunnen schrijven. Gewoonlijk vinden Ruby ontwikkelaars het leuk.
```

2021-04-02 20:25 UTC, noah-vdv commented on 1-js/01-getting-started/1-intro/article.md
> +- Dart](https://www.dartlang.org/) is een standalone taal die een eigen engine heeft die draait in niet-browseromgevingen (zoals mobiele apps), maar ook kan worden getransponeerd naar JavaScript. Ont
```suggestion
- Dart](https://www.dartlang.org/) is een standalone taal die een eigen engine heeft die draait in niet-browseromgevingen (zoals mobiele apps), maar ook kan worden getransporteerd naar JavaScript. Ontwikkeld door Google.
```
Same here

2024-11-12 12:55 UTC, closed without merging