Developer console
javascript-tutorial/nl.javascript.info pull request #5
Opened 2020-05-07 23:43 UTC by vertonghenb

2020-06-08 07:53 UTC, Paultje52 approved these changes
Everything is translated correctly

2020-07-12 21:04 UTC, RMo-Sloth commented
Some small modifications should be made to this translation. 

1. The translation tool used is mentioned below.
2. Some parts are translated too literal from English to sentences that have no meaning in Dutch. E.g. "De meeste ontwikkelaars leunen voor de"  on line 9 is improper Dutch.

2021-04-02 20:36 UTC, noah-vdv requested changes
Wikipedia link to Dutch and removing non important info

2021-04-02 20:36 UTC, noah-vdv commented on 1-js/01-getting-started/4-devtools/article.md
> +De code is gevoelig voor fouten. Je zult waarschijnlijk fouten maken... Oh, waar heb ik het over? Je gaat *absoluut* fouten maken, tenminste als je een mens bent, niet een [robot](https://en.wikipedi
```suggestion
De code is gevoelig voor fouten. Je zult waarschijnlijk fouten maken... Oh, waar heb ik het over? Je gaat *absoluut* fouten maken, tenminste als je een mens bent, niet een [robot](https://nl.wikipedia.org/wiki/Bender_(Futurama)).
```

2021-04-02 20:36 UTC, noah-vdv commented on 1-js/01-getting-started/4-devtools/article.md
```suggestion
```

2024-11-12 12:54 UTC, closed without merging